language: python

services:
 - mysql

python:
 - "3.8"

before_install:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS epam;'

install:
 - pip install -r requirements.txt
 - pip install pytest
 - pip install pytest-cov
 - pip install pylint

before_script:
  - python app.py &

script:
  - alembic init alembic
  - alembic revision --autogenerate
  - alembic upgrade head
  - pytest --cov=epam_project/rest/view.py tests/
  - pylint epam_project


