"""Setup file, responsible for installing all requirements and project"""
import setuptools
from setuptools import setup

setup(
    name='EPAM_PROJECT',
    version='1.0',
    packages=setuptools.find_packages(),
    url='https://github.com/RomanOstrovskyi/EPAM_PROJECT',
    license='',
    author='Roman Ostrovskyi',
    author_email='romaostrovskiy616@gmail.com',
    description='This is emap project!',
    install_requires=["alembic==1.9.4",
                      "astroid==2.14.2",
                      "attrs==22.2.0",
                      "certifi==2022.12.7",
                      "cffi==1.15.1",
                      "charset-normalizer==3.0.1",
                      "click==8.1.3",
                      "colorama==0.4.6",
                      "coverage==7.2.1",
                      "cryptography==39.0.2",
                      "dill==0.3.6",
                      "exceptiongroup==1.1.0",
                      "Faker==17.4.0",
                      "Flask==2.2.3",
                      "gunicorn==20.1.0",
                      "greenlet==2.0.2",
                      "idna==3.4",
                      "importlib-metadata==6.0.0",
                      "importlib-resources==5.12.0",
                      "iniconfig==2.0.0",
                      "isort==5.12.0",
                      "itsdangerous==2.1.2",
                      "Jinja2==3.1.2",
                      "jsonschema==4.17.3",
                      "lazy-object-proxy==1.9.0",
                      "Mako==1.2.4",
                      "MarkupSafe==2.1.2",
                      "marshmallow==3.19.0",
                      "mccabe==0.7.0",
                      "packaging==23.0",
                      "pkgutil-resolve-name==1.3.10v",
                      "platformdirs==3.0.0",
                      "pluggy==1.0.0",
                      "pycparser==2.21",
                      "pylint==2.16.3",
                      "pylint-runner==0.6.0",
                      "PyMySQL==1.0.2",
                      "pyrsistent==0.19.3",
                      "pytest==7.2.1",
                      "pytest-cov==4.0.0",
                      "python-coveralls==2.9.3",
                      "python-dateutil==2.8.2",
                      "PyYAML==6.0",
                      "requests==2.28.2",
                      "six==1.16.0",
                      "SQLAlchemy==2.0.4",
                      "tomli==2.0.1",
                      "tomlkit==0.11.6",
                      "vtyping-extensions==4.5.0",
                      "urllib3==1.26.14",
                      "Werkzeug==2.2.3",
                      "wrapt==1.15.0",
                      "zipp==3.15.0"
                      ]
)
